version: "3"
services:
  budget-app-npm:
    image: ${LOCAL_IMAGE_NAME:-filipemego/budget-app}
    tty: true
    user: node
    volumes:
      - ./app:/home/node/budget-app
    command:
      - /bin/ash
      - -c
      - npm run test:unit
